SELECT NVL(A.HOUR, D.HOUR) HOUR, NVL(A.CNT, 0) COUNT
FROM (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'hh24')) HOUR, COUNT(*) CNT
      FROM ANIMAL_OUTS
      GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'hh24'))) A RIGHT OUTER JOIN
      (SELECT LEVEL - 1 HOUR FROM DUAL CONNECT BY LEVEL < 25) D
ON A.HOUR = D.HOUR
ORDER BY HOUR;
