SELECT U.USER_ID, U.NICKNAME, 
       U.CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 전체주소,
       SUBSTR(U.TLNO,1,3) || '-' || SUBSTR(U.TLNO,4,4) || '-' || SUBSTR(U.TLNO,8,4) 전화번호
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME, U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2, U.TLNO 
HAVING COUNT(*) >= 3
ORDER BY U.USER_ID DESC
