SELECT HOUR, COUNT(*)
FROM (
        SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR   
        FROM ANIMAL_OUTS
        WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
     )
GROUP BY HOUR
ORDER BY HOUR
