SELECT  I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES,
        I.ADDRESS, R.SCORE
FROM REST_INFO I, (
                        SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE
                        FROM REST_REVIEW
                        GROUP BY REST_ID
                    ) R
WHERE I.ADDRESS LIKE '서울%'
AND I.REST_ID = R.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC
