SELECT T.CATEGORY, T.PRICE, T.PRODUCT_NAME
FROM (
            SELECT CATEGORY, PRICE, PRODUCT_NAME,
               RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) NUM
            FROM FOOD_PRODUCT
            WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
         ) T
WHERE T.NUM = 1
ORDER BY T.PRICE DESC
