SELECT T.HISTORY_ID, 
       T.DAILY_FEE * DURATION * NVL((1 - 
                        (SELECT P.DISCOUNT_RATE
                        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
                        WHERE T.CAR_TYPE = P.CAR_TYPE
                        AND P.DURATION_TYPE LIKE T.DISCOUNT) * 0.01) , 1) FEE
FROM (SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE, END_DATE - START_DATE + 1 DURATION,
           CASE
                WHEN END_DATE - START_DATE + 1>= 90 THEN '90일 이상'
                WHEN END_DATE - START_DATE + 1>= 30 THEN '30일 이상'
                WHEN END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'
           END DISCOUNT
    FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE C.CAR_TYPE = '트럭'
    AND H.CAR_ID = C.CAR_ID) T
ORDER BY FEE DESC, T.HISTORY_ID DESC
